global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Globalization;
global using System.Threading;
global using System.Threading.Tasks;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Windows.Foundation;
global using Uno.Extensions;
global using Uno.Toolkit.UI;
global using Uno.Extensions.Configuration;
global using Uno.Extensions.Hosting;
global using Uno.Extensions.Navigation;

global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Input;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Controls.Primitives;
global using Microsoft.UI.Xaml.Markup;
global using Microsoft.UI.Xaml.Data;
global using Microsoft.UI.Xaml.Media;
global using Application = Microsoft.UI.Xaml.Application;
